export const GET_SCHEDULES_SUBJECTS = "GET_SCHEDULES_SUBJECTS"
export const GET_SCHEDULES_SUBJECTS_SUCCESS = "GET_SCHEDULES_SUBJECTS_SUCCESS"
export const GET_SCHEDULES_SUBJECTS_FAIL = "GET_SCHEDULES_SUBJECTS_FAIL"

