export const GET_EXAM_MODEL = "GET_EXAM_MODEL"
export const GET_EXAM_MODEL_SUCCESS = "GET_EXAM_MODEL_SUCCESS"
export const GET_EXAM_MODEL_FAIL = "GET_EXAM_MODEL_FAIL"
export const GET_DOWNLOAD_EXAM = "GET_DOWNLOAD_EXAM"
export const GET_DOWNLOAD_EXAM_SUCCESS = "GET_DOWNLOAD_EXAM_SUCCESS"
export const GET_DOWNLOAD_EXAM_FAIL = "GET_DOWNLOAD_EXAM_FAIL"


