export const GET_SURVEYS = "GET_SURVEYS"
export const GET_SURVEYS_SUCCESS = "GET_SURVEYS_SUCCESS"
export const GET_SURVEYS_FAIL = "GET_SURVEYS_FAIL"
export const GET_SURVEY_QUESTIONS = "GET_SURVEY_QUESTIONS"
export const GET_SURVEY_QUESTIONS_SUCCESS = "GET_SURVEY_QUESTIONS_SUCCESS"
export const  POST_ANSWERS = 'POST_ANSWERS'


