export const GET_AREAS = "GET_AREAS"
export const GET_AREAS_SUCCESS = "GET_AREAS_SUCCESS"
export const GET_AREAS_FAIL = "GET_AREAS_FAIL"
export const POST_SUGGESTIONS = "POST_SUGGESTIONS"
export const API_ERROR = "SUGGESTIONS_API_ERROR"

