export const GET_PROMISSORY_NOTE = "GET_PROMISSORY_NOTE"
export const GET_PROMISSORY_NOTE_SUCCESS = "GET_PROMISSORY_NOTE_SUCCESS"
export const GET_PROMISSORY_NOTE_FAIL = "GET_PROMISSORY_NOTE_FAIL"
export const POST_PROMISSORY_NOTE_CARD = "POST_PROMISSORY_NOTE_CARD"
export const POST_PROMISSORY_NOTE_SUCCESS = "POST_PROMISSORY_NOTE_SUCCESS"
export const POST_PROMISSORY_NOTE_FAIL = "GET_PROMISSORY_NOTE_FAIL"
export const GET_INFO_PROMISSORY_NOTE = "GET_INFO_PROMISSORY_NOTE"
export const GET_INFO_PROMISSORY_NOTE_SUCCESS = "GET_INFO_PROMISSORY_NOTE_SUCCESS"
export const GET_INFO_PROMISSORY_NOTE_FAIL = "GET_INFO_PROMISSORY_NOTE_FAIL"


