export const GET_RAPIPAGO = "GET_RAPIPAGO"
export const GET_RAPIPAGO_SUCCESS = "GET_RAPIPAGO_SUCCESS"
export const GET_RAPIPAGO_FAIL = "GET_RAPIPAGO_FAIL"
export const POST_BARCODE = "POST_BARCODE"
export const POST_BARCODE_SUCCESS = "POST_BARCODE_SUCCESS"
export const POST_BARCODE_FAIL = "POST_BARCODE_FAIL"

