export const POST_SOFTWARE = "POST_SOFTWARE"
export const GET_SOFTWARE = "GET_SOFTWARE"
export const GET_SOFTWARE_SUCCESS = "GET_SOFTWARE_SUCCESS"
export const POST_REQUIREMENT = "POST_REQUIREMENT"


