export const GET_REINCORPORATION = "GET_REINCORPORATION"
export const GET_REINCORPORATION_SUCCESS = "GET_REINCORPORATION_SUCCESS"
export const GET_REINCORPORATION_FAIL = "GET_REINCORPORATION_FAIL"
export const POST_REINCORPORATION = "POST_REINCORPORATION"
export const SUGGESTIONS_API_ERROR = "SUGGESTIONS_API_ERROR"

