
export const ACADEMIC_INFO = "ACADEMIC_INFO"
export const ACADEMIC_INFO_SUCCESS = "ACADEMIC_INFO_SUCCESS"

export const INSCRIPTION_INFO = "INSCRIPTION_INFO"
export const INSCRIPTION_INFO_SUCCESS = "INSCRIPTION_INFO_SUCCESS"

