export const GET_FILE_DOCUMENTATION = "GET_FILE_DOCUMENTATION"
export const GET_FILE_DOCUMENTATION_SUCCESS = "GET_FILE_DOCUMENTATION_SUCCESS"
export const GET_FILE_DOCUMENTATION_FAIL = "GET_FILE_DOCUMENTATION_FAIL"


