
export const CHANGE_EMAIL = "CHANGE_EMAIL"
export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS"

export const PERSONAL_INFO = "PERSONAL_INFO"
export const PERSONAL_INFO_SUCCESS = "PERSONAL_INFO_SUCCESS"

export const PROVINCES = "PROVINCES"
export const PROVINCES_SUCCESS = "PROVINCES_SUCCESS"

export const LOCALITIES = "LOCALITIES"
export const LOCALITIES_SUCCESS = "LOCALITIES_SUCCESS"

export const NEIGHBOURS = "NEIGHBOURS"
export const NEIGHBOURS_SUCCESS = "NEIGHBOURS_SUCCESS"

export const PROV_LOC_NEI  = "PROV_LOC_NEI"
export const PROV_LOC_NEI_SUCCESS  = "PROV_LOC_NEI_SUCCESS"

//export const CLEAN_MODAL = "CLEAN_MODAL"

export const ADD_ADDRESS = "ADD_ADDRESS"
export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const DELETE_ADDRESS = "DELETE_ADDRESS"

export const ADD_PHONE = "ADD_PHONE"
export const UPDATE_PHONE = "UPDATE_PHONE"
export const DELETE_PHONE = "DELETE_PHONE"

export const CHANGE_PASS = "CHANGE_PASS"